name: Build Pick Pen File

on:
  issues:
    types: [opened, edited]
    label:
      - "pick"

permissions:
  contents: write
  pull-requests: write

jobs:
  pick-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse pick form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/pick.yml

      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install Python deps
        run: |
          pip install pyyaml
    
      - name: Build Pick Pen File
        shell: python
        run: |
          import yaml

          output_data = {
            "title": "${{ steps.issue-parser.outputs.issueparser_title }}",
            "url": "${{ steps.issue-parser.outputs.issueparser_url }}",
            "license": "${{ steps.issue-parser.outputs.issueparser_license }}",
            "shows": [
              {
                "episode": "${{ steps.issue-parser.outputs.issueparser_episode }}",
                "show": "${{ steps.issue-parser.outputs.issueparser_shows }}",
                "slug": "${{ steps.issue-parser.outputs.issueparser_shows }}".lower().replace(" ", "-"),
              }
            ],
            "description": "${{ steps.issue-parser.outputs.issueparser_description }}"
          }

          file_name = "${{ steps.issue-parser.outputs.issueparser_title }}.yaml".lower().replace(" ", "-")

          with open(f"./data/picks/{file_name}", 'w') as outfile:
            yaml.dump(output_data, outfile, default_flow_style=False, sort_keys=True, explicit_start=True)

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: generate pick file
          title: Add pick `${{ steps.issue-parser.outputs.issueparser_title }}`
          body: |
            Add pick `${{ steps.issue-parser.outputs.issueparser_title }}` from issue #${{ github.event.issue}}.
            This was automatically generated from the issue template.

            Closes #${{ github.event.issue.number }}
          base: main
          add-paths: |
            data/*
          labels: |
            pick
          branch: pick/${{ steps.issue-parser.outputs.issueparser_title }}_${{ github.event.issue.number }}
          delete-branch: true
